### ISSUE TITLE
ERROR: No matching distribution found for tfcochleagram

### ISSUE THREAD

**Issue by fatimahalqadheeb** [jenellefeather/tfcochleagram#1]
Hello, 

I am trying to generate the cochleagram waveforms for audio signals. I have tried to run your code but it there is an error on tfcochleagram I tried to install it using the command "!pip install tfcochleagram" and it fires this error
ERROR: Could not find a version that satisfies the requirement tfcochleagram (from versions: none)
ERROR: No matching distribution found for tfcochleagram

Another error while I am trying to fix the above issue I get this 
ImportError: cannot import name 'cochleagram' from 'pycochleagram' (unknown location)
when executing the command "import tfcochleagram"

**Comment by jenellefeather** [comment]
Hi! This repository is not set up with a pip install. If you clone the repository and navigate to the directory with the notebook (or otherwise add the module to the python path) then python will be able to find the code. 

Note that this code is written in tf1 (it is not updated for tf2), so when installing dependencies keep this in mind.
